spring:
  application:
    name: sharemap-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true # H2 web ui
      path: /h2-console

logging:
  level:
    root: DEBUG
    springbootkotlin:
      sharemapserver: DEBUG